---
- name: ssh config
  hosts: all
  become: yes
  tasks:
  - name: required variables
    debug:
      msg:
        - "hostname: {{ hostname }}"
        - "wd: {{ wd }}"
        - "ansible_distribution_release: {{ ansible_distribution_release }}"
    tags: general

  - name: stat /tmp/secret.json
    stat: 
      path: /tmp/secret.json
    register: secret

  - name: get secrets
    shell: "curl -H 'X-Vault-Token: {{ VAULT_TOKEN }}' -H 'X-Vault-Request: true' {{ VAULT_ADDR }}/v1/cubbyhole/{{ hostname }} | jq -rMc .data > /tmp/secret.json"
    args:
      executable: /bin/bash
    when: secret.stat.exists == False

  - name: write ssh host keys
    shell: "cat /tmp/secret.json | jq '.\"{{ item }}\"' > /etc/ssh/{{ item }}"
    args:
      executable: /bin/bash
    loop:
      - "ssh_host_ecdsa_key"
      - "ssh_host_ecdsa_key.cer"
      - "ssh_host_ed25519_key"
      - "ssh_host_ed25519_key.cer"
      - "ssh_host_rsa_key"
      - "ssh_host_rsa_key.cer"

  - name: set ssh host key cer permissions
    file:
      path: /etc/ssh/{{ item }}
      owner: root
      group: root
      mode: '0644'
    loop:
      - "ssh_host_ecdsa_key.cer"
      - "ssh_host_ed25519_key.cer"
      - "ssh_host_rsa_key.cer"

  - name: set ssh host key permissions
    file:
      path: /etc/ssh/{{ item }}
      owner: root
      group: root
      mode: '0600'
    loop:
      - "ssh_host_ecdsa_key"
      - "ssh_host_ed25519_key"
      - "ssh_host_rsa_key"

