---
- name: ssh config
  hosts: all
  become: yes
  tasks:
  - name: required variables
    debug:
      msg:
        - "hostname: {{ hostname }}"
        - "wd: {{ wd }}"
        - "ansible_distribution_release: {{ ansible_distribution_release }}"
    tags: general

  - name: stat /tmp/secret.json
    stat: 
      path: /tmp/secret.json
    register: secret

  - name: generate token
    shell: "python3 -m metal_cloud.vault -n {{ hostname }} -i"
    args:
      executable: /bin/bash
    when: generate_token|default(false)
    delegate_to: 127.0.0.1
    register: VAULT_TOKEN

  - name: get secrets
    shell: "curl -H 'X-Vault-Token: {{ VAULT_TOKEN }}' -H 'X-Vault-Request: true' {{ VAULT_ADDR }}/v1/cubbyhole/{{ hostname }} | jq -rMc .data > /tmp/secret.json"
    args:
      executable: /bin/bash
    when: secret.stat.exists == False

  - name: write ssh host keys
    shell: "cat /tmp/secret.json | jq '.\"{{ item }}\"' > /etc/ssh/{{ item }}"
    args:
      executable: /bin/bash
    loop:
      - "ssh_host_ecdsa_key"
      - "ssh_host_ecdsa_key.cer"
      - "ssh_host_ed25519_key"
      - "ssh_host_ed25519_key.cer"
      - "ssh_host_rsa_key"
      - "ssh_host_rsa_key.cer"

  - name: set ssh host key cer permissions
    file:
      path: /etc/ssh/{{ item }}
      owner: root
      group: root
      mode: '0644'
    loop:
      - "ssh_host_ecdsa_key.cer"
      - "ssh_host_ed25519_key.cer"
      - "ssh_host_rsa_key.cer"

  - name: set ssh host key permissions
    file:
      path: /etc/ssh/{{ item }}
      owner: root
      group: root
      mode: '0600'
    loop:
      - "ssh_host_ecdsa_key"
      - "ssh_host_ed25519_key"
      - "ssh_host_rsa_key"

  - name: touch /etc/ssh/ssh_known_hosts
    file:
      dest: /etc/ssh/ssh_known_hosts
      state: touch

  - name: setup global known_hosts
    lineinfile:
      path: /etc/ssh/ssh_known_hosts
      line: '@cert-authority * ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPhTMqNK5UADz2CqndLcf4X64ug2ERMD8VoWcruT7foI'

  - name: global ssh config require strict host key checking
    lineinfile:
      dest: /etc/ssh/ssh_config
      insertafter: "^Host *"
      regexp: "^# *StrictHostKeyChecking.*$"
      line: "    StrictHostKeyChecking yes"

