---
- hosts: all
  become: true
  tasks:
  - name: required variables
    debug:
      msg:
        - "nonrootuser: {{ nonrootuser }}"
        - "ansible_distribution_release: {{ ansible_distribution_release }}"
    tags: general

  - name: git config
    become_user: "{{ nonrootuser }}"
    command: "{{ item }}"
    with_items:
      - git config --global user.email "ezekielnewren@gmail.com"
      - git config --global user.name "Ezekiel Newren"
      - git config pull.rebase false
