- block:
  - name: set hostname
    shell: "echo {{ ansible_hostname }} > /etc/hostname"

  - name: make sure the ubuntu user doesn't exist
    user:
      name: "ubuntu"
      state: absent

  - name: install sudo
    package:
      name: sudo
      state: present

  - name: create nonrootuser
    user:
      name: "{{ nonrootuser }}"
      shell: /bin/bash
      password_lock: yes
      groups: wheel
      append: yes


  - name: allow the use of sudo without a password
    replace:
      path: "/etc/sudoers"
      regexp: "^(# *)?%wheel.*$"
      replace: "%wheel   ALL=(ALL:ALL) NOPASSWD: ALL"


  - name: hush login
    file:
      path: /home/{{ nonrootuser }}/.hushlogin
      owner: "{{ nonrootuser }}"
      group: "{{ nonrootuser }}"
      state: touch

  - name: copy .profile
    copy:
      src: .profile
      dest: /home/{{ nonrootuser }}/.profile
      owner: "{{ nonrootuser }}"
      group: "{{ nonrootuser }}"
      mode: "0644"

  - name: copy .bashrc
    copy:
      src: .bashrc
      dest: /home/{{ nonrootuser }}/.bashrc
      owner: "{{ nonrootuser }}"
      group: "{{ nonrootuser }}"
      mode: "0644"

  - name: copy .bash_aliases
    copy:
      src: .bash_aliases
      dest: /home/{{ nonrootuser }}/.bash_aliases
      owner: "{{ nonrootuser }}"
      group: "{{ nonrootuser }}"
      mode: "0644"

  #- set_fact:
  #    sshuser: "{{ nonrootuser }}"

  - name: run other roles
    include_role:
      name: "{{ role_other }}"
    loop:
      - ssh
      - sshd
      # - netplan
    loop_control:
      loop_var: role_other

  become: yes
  become_user: root
  tags:
    - baremetal
