- block:
  - set_fact:
      password: "{{ lookup('file', '/tmp/password') }}"

  - name: set root password
    user:
      name: "root"
      password: "{{ password | password_hash('sha512') }}"

  - name: set hostname
    shell: "echo {{ hostname }} > /etc/hostname"

  - name: make sure the ubuntu user doesn't exist
    user:
      name: "ubuntu"
      state: absent

  - name: create nonrootuser
    user:
      name: "{{ nonrootuser }}"
      shell: /bin/bash
      password_lock: yes
      groups: sudo
      append: yes

  - name: allow the use of sudo without a password
    replace:
      path: "/etc/sudoers"
      regexp: "^%sudo.*$"
      replace: "%sudo   ALL=(ALL:ALL) NOPASSWD: ALL"


  - name: hush login
    file:
      path: /home/{{ nonrootuser }}/.hushlogin
      owner: "{{ nonrootuser }}"
      group: "{{ nonrootuser }}"
      state: touch

  - name: bash aliases
    copy:
      src: .bash_aliases
      dest: /home/{{ nonrootuser }}/.bash_aliases
      owner: "{{ nonrootuser }}"
      group: "{{ nonrootuser }}"
      mode: "0644"

  - name: ensure that ufw is installed
    package:
      name: ufw
      state: present

  - name: enable firewall
    ufw:
      direction: incoming
      policy: deny
      state: enabled

  - name: allow dhcp
    shell: "{{ item }}"
    with_items:
      - "ufw allow bootps"
      - "ufw allow 53/tcp"
      - "ufw allow 53/udp"

  - name: allow forwarding of all packets
    replace:
      path: /etc/default/ufw
      regexp: 'DEFAULT_FORWARD_POLICY="DROP"'
      replace: 'DEFAULT_FORWARD_POLICY="ACCEPT"'

  - set_fact:
      sshuser: "{{ nonrootuser }}"

  - name: run other roles
    include_role:
      name: "{{ role_other }}"
    loop:
      - ssh
      - sshd
      - netplan
    loop_control:
      loop_var: role_other

  become: yes
  become_user: root
  tags:
    - baremetal
