- block:
  - set_fact:
      password: "{{ lookup('file', '/tmp/password') }}"

  - name: set root password
    user:
      name: "root"
      password: "{{ password | password_hash('sha512') }}"

  - name: set hostname
    shell: "echo {{ hostname }} > /etc/hostname"

  - name: create nonrootuser
    user:
      name: "{{ nonrootuser }}"
      shell: /bin/bash
      password_lock: yes
      groups: sudo
      append: yes

  - name: allow the use of sudo without a password
    replace:
      path: "/etc/sudoers"
      regexp: "^%sudo.*$"
      replace: "%sudo   ALL=(ALL:ALL) NOPASSWD: ALL"


  - name: hush login
    file:
      path: /home/{{ nonrootuser }}/.hushlogin
      owner: "{{ nonrootuser }}"
      group: "{{ nonrootuser }}"
      state: touch

  - name: bash aliases
    copy:
      src: .bash_aliases
      dest: /home/{{ nonrootuser }}/.bash_aliases
      owner: "{{ nonrootuser }}"
      group: "{{ nonrootuser }}"
      mode: "0644"

  - set_fact:
      sshuser: "{{ nonrootuser }}"

  - name: run other roles
    include_role:
      name: "{{ role_other }}"
    loop:
      - ssh
      - sshd
      - netplan
      - keyring
    loop_control:
      loop_var: role_other

  become: yes
  become_user: root
  tags:
    - baremetal