- block:
  - set_fact:
      password: "{{ lookup('file', '/tmp/password') }}"
    
  - name: set root password
    user:
      name: "root"
      password: "{{ password | password_hash('sha512') }}"

  - name: create nonrootuser
    user:
      name: "{{ nonrootuser }}"
      shell: /bin/bash
      password_lock: yes

  become: yes
  become_user: root
  tags:
    - baremetal
