- block:
  - set_fact:
      password: "{{ lookup('file', '/tmp/password') }}"
    
  - name: set root password
    user:
      name: "root"
      password: "{{ password | password_hash('sha512') }}"

  - name: create nonrootuser
    user:
      name: "{{ nonrootuser }}"
      shell: /bin/bash
      password_lock: yes

  - name: hush login
    file:
      path: /home/{{ nonrootuser }}/.hushlogin
      owner: "{{ nonrootuser }}"
      group: "{{ nonrootuser }}"
      state: touch

  - name: bash aliases
    copy:
      src: .bash_aliases
      dest: /home/{{ nonrootuser }}/.bash_aliases
      owner: "{{ nonrootuser }}"
      group: "{{ nonrootuser }}"
      mode: "0644"

  become: yes
  become_user: root
  tags:
    - baremetal
