---
- name: run roles
  hosts: ceph_cluster
  pre_tasks:
    - name: minimum ansible version
      vars:
        minver: "2.12.0"
      assert:
        that: "ansible_version.full is version_compare('{{ minver }}', '>=')"
        msg: "You must update Ansible to at least {{ minver }} to use this playbook."
    
    - name: print out extra_vars
      debug:
        msg:
          - "ansible_distribution: {{ ansible_distribution }}"
          - "ansible_distribution_release: {{ ansible_distribution_release }}"
          - "ansible_distribution_major_version: {{ ansible_distribution_major_version }}"

    - set_fact:
        CNODE: "{{ CNODE|default({}) | combine({item: lookup('dig', item)}) }}"
      with_items: "{{ play_hosts }}"

    - name: csv list of hosts
      debug:
        msg:
          - "{{ CNODE.keys() | join(',') }}"
          - "{{ CNODE.values() | join(',') }}"

  ## https://docs.ceph.com/en/latest/install/index_manual/
  
  roles:
    - ceph
    

