---
- name: run roles
  hosts: k8s_control_plane
  pre_tasks:
    - name: minimum ansible version
      vars:
        minver: "2.12.0"
      assert:
        that: "ansible_version.full is version_compare('{{ minver }}', '>=')"
        msg: "You must update Ansible to at least {{ minver }} to use this playbook."
    
    - name: print out extra_vars
      debug:
        msg:
          - "ansible_distribution: {{ ansible_distribution }}"
          - "ansible_distribution_release: {{ ansible_distribution_release }}"
          - "ansible_distribution_major_version: {{ ansible_distribution_major_version }}"
  
  tasks:
    - name: generate random password for keepalived
      set_fact:
        KEEPALIVED_PASSWORD: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'ascii_uppercase', 'ascii_digits'], length=22) }}"
      run_once: true
      delegate_to: localhost

    - name: copy keepalived.conf
      template:
        src: keepalived.conf
        dest: /etc/keepalived/keepalived.conf

    - name: restart keepalived
      systemd:
        name: keepalived
        state: reloaded
    
  become: yes
  become_user: root



