---
- name: run roles
  hosts: all
  pre_tasks:
    - name: minimum ansible version
      vars:
        minver: "2.12.0"
      assert:
        that: "ansible_version.full is version_compare('{{ minver }}', '>=')"
        msg: "You must update Ansible to at least {{ minver }} to use this playbook."
    
    - name: print out extra_vars
      debug:
        msg:
          - "{{ role_list }}"
          - "ansible_distribution: {{ ansible_distribution }}"
          - "ansible_distribution_release: {{ ansible_distribution_release }}"
          - "ansible_distribution_major_version: {{ ansible_distribution_major_version }}"

  tasks:
    - name: include roles
      include_role:
        name: "{{ role_item }}"
      loop: "{{ role_list }}"
      loop_control:
        loop_var: role_item
