- block:
  - name: required variables
    debug:
      msg:
        - "ansible_hostname: {{ ansible_hostname }}"
  
  - name: copy EzekielNewrenRoot.pem
    copy:
      src: "EzekielNewrenRoot.pem"
      dest: "/etc/pki/ca-trust/source/anchors/"
      owner: root
      group: root
      mode: '0444'
  
  - name: update-ca-trust
    shell: "update-ca-trust"
    
  become: yes
  become_user: root
  tags:
    - pki

