- block:
  - name: install ca-certificates
    package:
      name: ca-certificates

  - name: copy certificate authority files
    copy:
      src: "{{ item }}"
      dest: "/etc/ssl/certs/{{ item }}"
      owner: root
      group: root
      mode: '0644'
    loop:
      - vault_intermediate.crt
      - vault_root.crt

  ## it says changed everytime but the file never gets bigger
  - name: add certificate authority files to ca-certificates.crt
    blockinfile:
      block: "{{ lookup('ansible.builtin.file', '{{ item }}') }}"
      path: /etc/ssl/certs/ca-certificates.crt
    loop:
      - vault_intermediate.crt
      - vault_root.crt

