- block:
  - name: required variables
    debug:
      msg:
        - "sshuser: {{ sshuser }}"

  - name: authorized_key
    authorized_key:
      user: "{{ sshuser }}"
      state: present
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAkr+o7iAJOYWY27TEl2d/8TdUTvCsOTJdgJByg+eV5I ezekielnewren@gmail.com"

  become: yes
  become_user: root
  tags:
    - ssh

