- set_fact:
    NETWORK: "{{ lookup('file', 'roles/nmcli/files/{{ inventory_hostname }}.yaml') | from_yaml }}"

- set_fact:
    ether_mac: "{{ NETWORK['network'] | map(attribute='ether') | flatten }}"
    wlan_mac: "{{ NETWORK['network'] | map(attribute='wlan') | select('defined') | flatten }}"

- name: setup udev rules to make interface names based on mac addresses
  template:
    src: 10-eth-mac.rules
    dest: /etc/udev/rules.d/10-eth-mac.rules
    owner: root
    group: root
    mode: '0644'
  become: yes
  become_user: root

- include_tasks: add_bridge.yaml
  loop: "{{ NETWORK['network'] }}"
  loop_control:
    loop_var: bridge


