- block:
  - name: lookup secrets directly
    set_fact:
      MACHINE_SECRET: "{{ lookup('hashivault', '{{ inventory_hostname }}', mount_point='/kv/machine', version=2) }}"
  
  - set_fact:
      NETWORK: "{{ MACHINE_SECRET['network'] }}"

  - set_fact:
      mac_addresses: "{{ mac_addresses | default([]) + item.macaddress }}"
    loop: "{{ NETWORK.values() | list }}"
    when: item.macaddress is defined

  - name: setup udev rules to make interface names based on mac addresses
    template:
      src: 10-eth-mac.rules
      dest: /etc/udev/rules.d/10-eth-mac.rules
      owner: root
      group: root
      mode: '0644'

  - name: create bridge br-fast
    nmcli:
      type: bridge
      conn_name: br-fast
      ifname: br-fast
      stp: true
      ip4: "{{ NETWORK['br-fast']['ipv4'] }}"
      state: present

  - name: add interfaces to br-fast
    nmcli:
      type: ethernet
      conn_name: "br-fast-{{ item | replace(':', '') }}"
      ifname: "e{{ item | replace(':', '')}}"
      master: "br-fast"
      slave_type: bridge
      state: present
    loop: "{{ NETWORK['br-fast']['macaddress'] }}"

  - name: create bridge br-mgmt
    nmcli:
      type: bridge
      conn_name: br-mgmt
      ifname: br-mgmt
      stp: true
      # ip4: "{{ NETWORK['br-mgmt']['ipv4'] }}"
      method4: auto
      state: present

  - name: add interfaces to br-mgmt
    nmcli:
      type: ethernet
      conn_name: "br-mgmt-{{ item | replace(':', '') }}"
      ifname: "e{{ item | replace(':', '')}}"
      master: "br-mgmt"
      slave_type: bridge
      state: present
    loop: "{{ NETWORK['br-mgmt']['macaddress'] }}"

  become: yes
  become_user: root









