# sudo kubeadm init --config=/tmp/kubeadm-init.yaml --node-name `hostname`.{{ SLD }}
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
skipPhases:
  - certs
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: v1.30.0
controlPlaneEndpoint: "{{ K8S_SECRET['topology']['endpoint'] }}.{{ SLD }}:6443"
apiServer:
  extraArgs:
    bind-address: 0.0.0.0
    authorization-mode: "Node,RBAC"
    service-node-port-range: "1-49151"
networking:
  podSubnet: "172.20.0.0/16"
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
tlsCertFile: /etc/kubernetes/pki/kubelet-server.crt
tlsPrivateKeyFile: /etc/kubernetes/pki/kubelet-server.key

