- block:
  ## run gnome-keyring inside a docker container
  ## https://unix.stackexchange.com/a/548005/293827
  - name: ensure /root/bootup exists
    file:
      path: /root/bootup
      recurse: no
      state: directory

  - name: copy keyring.sh
    copy:
      src: "{{ item }}"
      dest: /root/bootup
      owner: root
      group: root
    loop:
      - keyring.sh
      - root-keyring.sh

  - name: set dbus environment variable
    lineinfile:
      path: /root/.profile
      line: "source /root/dbus.sh"

  - name: copy keyring.service
    copy:
      src: "keyring.service"
      dest: /etc/systemd/system
      owner: root
      group: root

  - name: enable and start keyring.service
    systemd:
      name: keyring
      daemon_reload: yes
      enabled: yes
      state: started

  become: yes
  become_user: root
  tags:
    - keyring

