- block:
  - set_fact:
      HOME: "/home/{{ nonrootuser }}"

  - name: copy keyring.sh
    copy:
      src: .keyring
      dest: "{{ HOME }}/"
      mode: '0755'

  - name: ensure bash aliases exists
    file:
      path: "{{ HOME }}/.bash_aliases"
      state: touch

  - name: source .keyring
    lineinfile:
      path: "{{ HOME }}/.bash_aliases"
      line: "source {{ HOME }}/.keyring"

  become: yes
  become_user: "{{ nonrootuser }}"
  tags:
    - keyring

