- block:
  - name: required variables
    debug:
      msg:
        - "macaddress: {{ macaddress }}"
        - "ansible_distribution_release: {{ ansible_distribution_release }}"

  - name: copy netplan template
    template:
      src: "60-dhcp-bridge.yaml"
      dest: /etc/netplan/60-dhcp-bridge.yaml
      owner: root
      group: root
      mode: '0600'

  become: yes
  become_user: root
  tags:
    - netplan

