- block:
  - name: required variables
    debug:
      msg:
        - "ansible_distribution_release: {{ ansible_distribution_release }}"

  - include_role:
      name: ipforward

  - name: disable selinux in the config file
    lineinfile:
      path: /etc/selinux/config
      regexp: '^SELINUX=enforcing$'
      line: 'SELINUX=permissive'

  - name: disable selinux right now
    shell: setenforce 0

  - name: disable firewalld right now
    systemd:
      name: firewalld
      enabled: false
      state: stopped

  - name: copy network manager file
    copy:
      src: calico.conf
      dest: "/etc/NetworkManager/conf.d/"
      owner: root
      group: root
      mode: '0644'

  - name: copy kubernetes.repo, crio.repo
    copy:
      src: "{{ item }}"
      dest: "/etc/yum.repos.d/"
      owner: root
      group: root
      mode: '0644'
    loop:
      - kubernetes.repo
      - crio.repo

  - name: install container runtime
    package:
      name:
        - cri-o
        - docker

  - name: find container image alias files
    find:
      paths: /etc/containers/registries.conf.d
      patterns: "[0-9]{3}-.*$"
      use_regex: yes
    register: file_match

  - name: remove container image aliases
    file:
      path: "{{ item.path }}"
      state: absent
    loop: "{{ file_match.files }}"
    when: file_match.matched > 0

  - name: install kubernetes
    package:
      name:
        - kubeadm
        - kubectl
        - kubelet
      state: present

  - name: enable and start kubelet, crio
    systemd:
      name: "{{ item }}"
      enabled: true
      state: started
    loop:
      - kubelet
      - crio

  become: yes
  become_user: root
  tags:
    - kubernetes

