- block:
  - name: required variables
    debug:
      msg:
        - "ansible_distribution_release: {{ ansible_distribution_release }}"

  - include_role:
      name: ipforward

  - name: disable selinux in the config file
    lineinfile:
      path: /etc/selinux/config
      regexp: '^SELINUX=enforcing$'
      line: 'SELINUX=permissive'

  - name: disable selinux right now
    shell: setenforce 0

  - name: disable firewalld right now
    systemd:
      name: firewalld
      enabled: false
      state: stopped

  - name: copy network manager file
    copy:
      src: calico.conf
      dest: "/etc/NetworkManager/conf.d/"
      owner: root
      group: root
      mode: '0644'

  - name: copy crio.repo
    copy:
      src: "crio.repo"
      dest: "/etc/yum.repos.d/"
      owner: root
      group: root
      mode: '0644'

  - name: install cri-o
    package:
      name:
        - cri-o

  - include_role:
      name: kubernetes-client

  - name: install kubernetes
    package:
      name:
        - kubeadm
        - kubelet
      state: present

  - name: enable and start kubelet, crio
    systemd:
      name: "{{ item }}"
      enabled: true
      state: started
    loop:
      - kubelet
      - crio

  become: yes
  become_user: root
  tags:
    - kubernetes

