- block:
  - name: create containers
    luks_device:
      device: "/dev/disk/by-id/{{item.value['bus'] }}-{{ item.key }}"
      type: "luks2"
      name: "{{ item.key }}"
      state: "opened"
      passphrase: "{{ item.value['password'] }}"
      hash: "sha256"
      pbkdf:
        algorithm: "pbkdf2"
        iteration_count: 1000  ## the minimum allowed by luks
    with_dict: "{{ FDE }}"
    no_log: true

  - name: create group for each device
    lvg:
      vg: "{{ item.key }}"
      pvs: "/dev/mapper/{{ item.key }}"
      state: present
    with_dict: "{{ FDE }}"

  - name: create volume for each group
    lvol:
      vg: "{{ item.key }}"
      lv: "data"
      size: "100%VG"
      state: "present"
    with_dict: "{{ FDE }}"

  become: yes
  become_user: root
  tags:
    - ceph
