- set_fact:
    CEPH_VERSION: "17.2.0"
    CODENAME: "focal"  ## this is derived from CEPH_VERSION i.e. debian-{{ CEPH_VERSION }}/dists/<pick_a_codename>/main
    CLUSTER_NAME: "veritas"
    FSID: "ca98662e-19f3-47e3-a029-880ff75396ce"

- include: get_packages.yaml
- include: monitor_bootstrapping.yaml

