- block:
  - set_fact:
      CEPH_VERSION: "17.2.0"
      CODENAME: "focal"  ## this is derived from CEPH_VERSION i.e. debian-{{ CEPH_VERSION }}/dists/<pick_a_codename>/main

  - name: add ceph key
    apt_key:
      url: https://download.ceph.com/keys/release.asc
      id: 08B73419AC32B4E966C1A330E84AC2C0460F3994
      state: present
  
  - name: add ceph repo
    apt_repository:
      repo: "deb [arch={{ ansible_architecture }} signed-by=08B73419AC32B4E966C1A330E84AC2C0460F3994] https://download.ceph.com/debian-{{ CEPH_VERSION }} {{ CODENAME }} main"
      update_cache: yes
      state: present

  become: yes
  become_user: root
  tags:
    - ceph
