- block:
  ## https://openwrt.org/docs/techref/driver.wlan/start
  ## https://www.cyberciti.biz/faq/linux-find-wireless-driver-chipset/
  ## sudo lshw -C network | grep -B 1 -A 12 'Wireless interface'
  - name: wireless tools
    package:
      name: "{{ item }}"
    loop:
      ## ORDER MATTERS!!!
      - wireless-tools
      - iw-full
      - iwinfo
      - wpad

  - name: wireless drivers Atheros
    package:
      name: "{{ item }}"
    loop:
      - kmod-ath10k
      - kmod-ath3k
      - kmod-ath5k
      - kmod-ath9k

  - name: wireless drivers Ralink
    package:
      name: "{{ item }}"
    loop:
      - kmod-rt2400-pci
      - kmod-rt2500-pci
      - kmod-rt2500-usb
      - kmod-rt2800-lib
      - kmod-rt2800-mmio
      - kmod-rt2800-pci
      - kmod-rt2800-usb
      - kmod-rt2x00-lib
      - kmod-rt2x00-mmio
      - kmod-rt2x00-pci
      - kmod-rt2x00-usb
      - kmod-rt61-pci
      - kmod-rt73-usb

  - name: wireless drivers b43
    package:
      name: "{{ item }}"
    loop:
      - kmod-b43
      - kmod-b43legacy

  - name: smart card drivers
    package:
      name: "{{ item }}"
    loop:
      - pcscd
      - ccid
      - libopensc-pkcs11
      - opensc-utils-pkcs11-tool
      - p11-kit
      - gnutls-utils

- block:
  - name: install ansible
    pip:
      name:
        - ansible
        - ansible-modules-hashivault

  - name: remove luci
    opkg:
      name: "{{ item }}"
      state: absent
    loop:
      ## ORDER MATTERS!!!
      - luci-ssl
      - luci
      - luci-app-firewall
      - luci-app-opkg
      - luci-mod-admin-full
      - luci-mod-network
      - luci-mod-status
      - luci-mod-system
      - luci-proto-ipv6
      - luci-proto-ppp
      - luci-theme-bootstrap
      - luci-base
      - luci-lib-base
      - luci-lib-ip
      - luci-lib-jsonc
      - luci-lib-nixio

  - name: remove dropbear
    opkg:
      name: dropbear
      state: absent
  
  - name: install openssh-server
    opkg:
      name: openssh-server

  - name: install nice to have packages
    opkg:
      name: "{{ item }}"
    loop:
      - jq
      - git
      - git-http
      - file
      - nano
      - nmap
      - rsync
      - usbutils
      - pciutils

- name: run other roles
  include_role:
    name: "{{ role_other }}"
  loop:
    - pki
    - ssh
  loop_control:
    loop_var: role_other

