- block:
  - name: install dependencies
    apt:
      pkg:
        - ca-certificates
        - curl
        - gnupg
        - gnupg2
  
  - name: add docker key
    shell: curl https://download.docker.com/linux/ubuntu/gpg | gpg2 --dearmor -o- > /etc/apt/trusted.gpg.d/docker.gpg
  
  - name: get sha256sum of docker.gpg
    stat:
      path: /etc/apt/trusted.gpg.d/docker.gpg
      checksum_algorithm: sha256
      get_checksum: yes
    register: docker_stat
  
  - name: verify docker.gpg
    fail:
      msg: "docker.gpg hash mismatch"
    when: docker_stat.stat.checksum != "a09e26b72228e330d55bf134b8eaca57365ef44bf70b8e27c5f55ea87a8b05e2"
  
  - name: add docker repo
    apt_repository:
      # repo: "deb [arch={{ ansible_architecture }} signed-by=9DC858229FC7DD38854AE2D88D81803C0EBFCD88] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      repo: "deb [signed-by=9DC858229FC7DD38854AE2D88D81803C0EBFCD88] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      update_cache: yes
      state: present
  
  - name: install docker
    package:
      name:
        - docker.io
      state: present
  
  - name: determine availble groups
    getent:
      database: group
  
  - name: determine available users
    getent:
      database: passwd
  
  - name: ensure that docker group exists
    group:
      name: docker
    when: "'docker' not in ansible_facts.getent_group"
  
  - name: add nonrootuser to docker group
    user:
      name: "{{ nonrootuser }}"
      groups: docker
      append: yes
  
  become: yes
  become_user: root
  tags:
    - docker
  
  
  
  
  
  
  
  
