- block:
  - name: install dependencies
    apt:
      pkg:
        - ca-certificates
        - curl
        - gnupg
        - gnupg2
  
  - name: add docker key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      state: present
  
  - name: add docker repo
    apt_repository:
      # repo: "deb [arch={{ ansible_architecture }} signed-by=9DC858229FC7DD38854AE2D88D81803C0EBFCD88] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      repo: "deb [signed-by=9DC858229FC7DD38854AE2D88D81803C0EBFCD88] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      update_cache: yes
      state: present
  
  - name: install docker
    package:
      name:
        - docker.io
      state: present
  
  - name: determine availble groups
    getent:
      database: group
  
  - name: determine available users
    getent:
      database: passwd
  
  - name: ensure that docker group exists
    group:
      name: docker
    when: "'docker' not in ansible_facts.getent_group"
  
  - name: add nonrootuser to docker group
    user:
      name: "{{ nonrootuser }}"
      groups: docker
      append: yes
  
  become: yes
  become_user: root
  tags:
    - docker
  
  
  
  
  
  
  
  
