- name: required variables
  debug:
    msg:
      - "nonrootuser: {{ nonrootuser }}"
      - "ansible_distribution_release: {{ ansible_distribution_release }}"
      - "ansible_architecture: {{ ansible_architecture }}"

