- block:
  - name: update /etc/crypttab
    ansible.builtin.lineinfile:
      path: /etc/crypttab
      line: "{{ item['mnsn'] }} {{ item['path'] }} none tpm2-device=auto,discard,nofail"
    loop: "{{ DRIVE[1:] }}"

#  sudo systemctl list-units | grep systemd-cryptsetup
#  sudo systemctl daemon-reload

  become: yes
  become_user: root
  no_log: true
  tags:
    - fde

