- block:
  - name: create luks container
    luks_device:
      type: "luks2"
      device: "{{ item.value['path'] }}"
      name: "{{ item.key }}"
      label: "{{ item.key }}"
      state: "opened"
      passphrase: "{{ item.value['password'] }}"
    with_dict: "{{ SECRET['fde'] }}"

  - name: kill slot 1 on all devices
    shell: "echo -n {{ item.value['password'] }} | cryptsetup luksKillSlot {{ item.value['path'] }} 1"
    with_dict: "{{ SECRET['fde'] }}"
    register: result_killslot
    failed_when: false
    changed_when: result_killslot.rc == 0

  - name: run clevis luks bind on all drives for slot 1 unconditionally
    shell: "echo -n '{{ item.value['password'] }}' | clevis luks bind -s 1 -k - -d {{ item.value['path'] }} tpm2 '{}'"
    with_dict: "{{ SECRET['fde'] }}"

  - name: add drive to /etc/crypttab
    lineinfile:
      path: "/etc/crypttab"
      line: "{{ item.key }} {{ item.value['path'] }} none luks"
    with_dict: "{{ SECRET['fde'] }}"

  become: yes
  become_user: root
  no_log: true
  tags:
    - fde
