- name: install jq tpm2 and clevis packages
  package:
    name:
      - jq
  become: yes
  become_user: root

- name: read secrets from vault
  set_fact:
    SECRET: "{{ lookup('hashivault', '{{ inventory_hostname }}', mount_point='/kv/machine', version=2) }}"

- name: Combine all device information into a single list
  set_fact:
    DRIVE: "{{ ([SECRET['fde'].boot] + SECRET['fde'].nvme + SECRET['fde'].ssd + SECRET['fde'].hdd) }}"
  no_log: true

- name: add the path to the machine secrets dictionary
  set_fact:
    DRIVE: "{{ DRIVE | map('combine', {'path': '/dev/disk/by-id/' ~ item.bus ~ '-' ~ item.mnsn}) | list }}"
  loop: "{{ DRIVE }}"
  no_log: true

- name: stat all block devices
  stat:
    path: "{{ item['path'] }}"
    follow: yes
  loop: "{{ DRIVE }}"
  no_log: true
  register: stat_result

- name: add stat result to secrets dictionary
  set_fact:
    DRIVE: "{{ DRIVE | combine({'stat': item['stat']}) }}"
  with_items: "{{ stat_result.results }}"
  no_log: true

#- include: fde.yaml
#- include: lvm.yaml
