---
- hosts: all
  name: libvirt
  become: true
  pre_tasks:
    - name: minimum ansible version
      vars:
        minver: "2.12.0"
      assert:
        that: "ansible_version.full is version_compare('{{ minver }}', '>=')"
        msg: "minimum ansible version {{ minver }}"
    - name: required variables
      debug:
        msg:
          - "wd: {{ wd }}"
          - "ansible_distribution_release: {{ ansible_distribution_release }}"
  tasks:
    - name: ensure /root/bootup exists
      file:
        path: /root/bootup
        recurse: no
        state: directory
  
    - name: copy keyring.sh
      copy:
        src: "{{ wd }}/systemd/keyring.sh"
        dest: /root/bootup
        owner: root
        group: root
  
    - name: copy keyring.service
      copy:
        src: "{{ wd }}/systemd/keyring.service"
        dest: /etc/systemd/system
        owner: root
        group: root
    
    - name: enable and start keyring.service
      systemd:
        name: keyring
        daemon_reload: yes
        enabled: yes
        state: started

