---
- hosts: all
  name: virtualbox
  become: true
  pre_tasks:
    - name: minimum ansible version
      vars:
        minver: "2.12.0"
      assert:
        that: "ansible_version.full is version_compare('{{ minver }}', '>=')"
        msg: "minimum ansible version {{ minver }}"
    - name: required variables
      debug:
        msg:
          - "nonrootuser: {{ nonrootuser }}"
          - "ansible_distribution_release: {{ ansible_distribution_release }}"
  tasks:
    - name: add virtualbox signing key
      apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        id: B9F8D658297AF3EFC18D5CDFA2F683C52980AECF
        state: present
  
    - name: add virtualbox repo
      apt_repository:
        repo: "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian focal contrib"
        update_cache: yes
        state: present

    - name: install virtualbox
      package:
        name:
          - virtualbox-qt
        state: latest





