- block:
  - name: required variables
    debug:
      msg:
        # - "nonrootuser: {{ nonrootuser }}"
        - "ansible_distribution_release: {{ ansible_distribution_release }}"
    tags: general

  - name: install pip modules
    pip:
      name:
        - ansible-modules-hashivault
        - dnspython
        - kubernetes
      

  become: yes
  become_user: root

