- block:
  - name: install curl, jq
    package:
      name:
        - curl
        - jq

  become: yes
  become_user: root
  tags:
    - sshd

- block:
  - name: required variables
    debug:
      msg:
        - "hostname: {{ hostname }}"

  - name: stat /tmp/secret.json
    stat:
      path: /tmp/secret.json
    register: secret

  - name: lookup secrets directly
    set_fact:
      SSHD_KEYS: "{{ lookup('hashivault', '{{ hostname }}', mount_point='/service/machine', version=2) }}"
    when: secret.stat.exists == False

  - name: copy secrets to guest
    copy: content="{{ SSHD_KEYS }}" dest=/tmp/secret.json
    when: secret.stat.exists == False

  - name: check that /tmp/secret.json actually contains secrets
    command: grep "ssh_host" /tmp/secret.json

  tags:
    - sshd

- block:
  - name: write ssh host keys
    shell: "cat /tmp/secret.json | jq -r '.\"{{ item }}\"' > /etc/ssh/{{ item }}"
    loop:
      - "ssh_host_ecdsa_key"
      - "ssh_host_ecdsa_key.cer"
      - "ssh_host_ed25519_key"
      - "ssh_host_ed25519_key.cer"
      - "ssh_host_rsa_key"
      - "ssh_host_rsa_key.cer"

  - name: set ssh host key cer permissions
    file:
      path: /etc/ssh/{{ item }}
      owner: root
      group: root
      mode: '0644'
    loop:
      - "ssh_host_ecdsa_key.cer"
      - "ssh_host_ed25519_key.cer"
      - "ssh_host_rsa_key.cer"

  - name: delete ssh_host_key.pub files
    file:
      path: /etc/ssh/{{ item }}
      state: absent
    loop:
      - "ssh_host_ecdsa_key.pub"
      - "ssh_host_ed25519_key.pub"
      - "ssh_host_rsa_key.pub"

  - name: set ssh host key permissions
    file:
      path: /etc/ssh/{{ item }}
      owner: root
      group: root
      mode: '0600'
    loop:
      - "ssh_host_ecdsa_key"
      - "ssh_host_ed25519_key"
      - "ssh_host_rsa_key"

  - name: touch /etc/ssh/ssh_known_hosts
    file:
      dest: /etc/ssh/ssh_known_hosts
      state: touch

  - name: setup global known_hosts
    lineinfile:
      path: /etc/ssh/ssh_known_hosts
      line: '@cert-authority * ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPhTMqNK5UADz2CqndLcf4X64ug2ERMD8VoWcruT7foI'

  - name: touch /etc/ssh/ssh_config
    file:
      path: /etc/ssh/ssh_config
      state: touch

  - name: global ssh config require strict host key checking
    lineinfile:
      dest: /etc/ssh/ssh_config
      insertafter: "^Host *"
      regexp: "^# *StrictHostKeyChecking.*$"
      line: "    StrictHostKeyChecking yes"

  - name: copy sshd_config
    copy:
      src: "sshd_config"
      dest: "/etc/ssh/sshd_config"
      owner: root
      group: root
      mode: '0644'

  - stat:
      path: /etc/cloud/cloud.cfg
    register: result

  - name: do not delete ssh keys cloud init
    lineinfile:
      dest: /etc/cloud/cloud.cfg
      line: "ssh_deletekeys: false"
    when: result.stat.exists == True

  - name: ufw allow port 22
    ufw:
      rule: allow
      port: '22'
      proto: tcp
    when: ansible_facts["os_family"] == "Debian"

  - name: firewalld allow port 22
    firewalld:
      service: ssh
      permanent: yes
      state: enabled
    when: ansible_facts["os_family"] == "RedHat"

  become: yes
  become_user: root
  tags:
    - sshd

